# Generated by Django 2.1.2 on 2018-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20181030_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.TextField(),
        ),
    ]
